# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: unless-stopped
#     networks:
#       - atomic-clock-network
#     volumes:
#       - ./backend/app:/app/app

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - atomic-clock-network
#     volumes:
#       - ./frontend/src:/app/src

# networks:
#   atomic-clock-network:
#     driver: bridge

# services:
#   backend:
#     build: ./backend
#     expose:
#       - "8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     restart: unless-stopped
#     networks:
#       - atomic-clock-network

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - atomic-clock-network

# networks:
#   atomic-clock-network:
#     driver: bridge

# services:
#   backend:
#     build: ./backend
#     container_name: backend
#     hostname: backend
#     ports:
#       - "8000:8000"
#     environment:
#       - PYTHONUNBUFFERED=1
#     networks:
#       - atomic-clock-network

#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports:
#       - "3001:80"
#     environment:
#       - REACT_APP_API_URL=http://backend:8000
#     depends_on:
#       - backend
#     networks:
#       - atomic-clock-network

# networks:
#   atomic-clock-network:
#     driver: bridge

services:
  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "8000:8000"
    networks:
      - atomic-clock-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_API_URL=/api
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - atomic-clock-network
    stdin_open: true
    tty: true

networks:
  atomic-clock-network:
    driver: bridge